# 1 "D:\\Installations\\Symbian\\proj\\thesis\\AppAgent_ui_s80\\res\\BPA_caption.rss"
/* Copyright (c) 2006, Omar Mukhtar, NetLab - HUT. All rights reserved */

# 1 "D:\\Installations\\Symbian\\7.0s\\S80_DP2_0_SDK\\\\epoc32\\include\\apcaptionfile.rh" 1
// APCAPTIONFILE.RH
//
// Copyright (c) 2000 Symbian Ltd.  All rights reserved.
//
//

/** 
* Contains definitions for the resource files that are input to 
* caption files for Series 60
*/


/**
@internalComponent
*/


/**
@publishedAll
@released
*/
STRUCT CAPTION_DATA
	{
	LTEXT caption(256 )="";
	LTEXT shortcaption(256 )="";
	}
# 3 "D:\\Installations\\Symbian\\proj\\thesis\\AppAgent_ui_s80\\res\\BPA_caption.rss" 2


RESOURCE CAPTION_DATA
{
    caption="Bundle Protocol Application";
    shortcaption="BPA App";
}
